import type {
  Device,
  Vulnerability,
  ScanStatus,
  ScanReport,
  NetworkInterface,
  LogEntry,
  DashboardStats,
  ActivityItem,
  Settings,
} from '@/types';
import { AI_RISK_FACTORS } from './aiKnowledgeBase';
export const mockDevices: Device[] = [
  {
    id: 'dev-001',
    ip: '192.168.1.1',
    mac: 'AA:BB:CC:DD:EE:01',
    vendor: 'Cisco',
    type: 'router',
    hostname: 'main-router',
    os: 'IOS 15.7',
    ports: [
      { number: 22, protocol: 'tcp', state: 'open', service: 'SSH', version: 'OpenSSH 8.2' },
      { number: 80, protocol: 'tcp', state: 'open', service: 'HTTP', version: 'nginx 1.18' },
      { number: 443, protocol: 'tcp', state: 'open', service: 'HTTPS' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-cisco-001',
        cve_id: 'CVE-2023-20198',
        severity: 'critical',
        cvss_score: 10.0,
        description: 'Privilege escalation vulnerability in Cisco IOS XE Web UI',
        remediation: 'Disable HTTP/HTTPS Server or update to latest IOS XE release',
        affected_devices: ['dev-001'],
        references: ['https://nvd.nist.gov/vuln/detail/CVE-2023-20198'],
        published_date: '2023-10-16',
        last_modified: '2023-10-20',
        aiRiskScore: 0.98,
        confidence: 'HIGH',
        category: 'vulnerability',
        status: 'confirmed'
      },
      {
        id: 'vuln-cisco-002',
        cve_id: 'SSH-EXP-001',
        severity: 'medium',
        cvss_score: 5.0,
        description: 'SSH service detected on default port 22',
        remediation: 'Ensure strong passwords or keys are used. Consider moving to non-standard port.',
        affected_devices: ['dev-001'],
        references: [],
        published_date: '2024-01-01',
        last_modified: '2024-01-01',
        aiRiskScore: 0.4,
        confidence: 'HIGH',
        category: 'exposure',
        status: 'confirmed'
      },
      {
        id: 'vuln-cisco-legacy-001',
        cve_id: 'CVE-2005-1234',
        severity: 'low',
        cvss_score: 2.5,
        description: 'Legacy TCP timestamp vulnerability',
        remediation: 'Disable TCP timestamps if not needed',
        affected_devices: ['dev-001'],
        references: [],
        published_date: '2005-05-01',
        last_modified: '2005-06-01',
        aiRiskScore: 0.1,
        confidence: 'LOW',
        category: 'vulnerability',
        status: 'unverified'
      }
    ],
    riskLevel: 'critical',
    services: ['SSH', 'HTTP', 'HTTPS'],
    lastSeen: new Date().toISOString(),
    firstSeen: '2024-01-15T10:30:00Z',
    aiConfidence: 0.95,
    osPrediction: { os: 'Cisco IOS', confidence: 0.9 },
    detectedVendor: 'Cisco Systems',
    mlFeatures: ['router_ports', 'ssh', 'http']
  },
  {
    id: 'dev-002',
    ip: '192.168.1.10',
    mac: 'AA:BB:CC:DD:EE:02',
    vendor: 'Hikvision',
    type: 'camera',
    hostname: 'front-door-cam',
    ports: [
      { number: 80, protocol: 'tcp', state: 'open', service: 'HTTP' },
      { number: 554, protocol: 'tcp', state: 'open', service: 'RTSP' },
      { number: 8000, protocol: 'tcp', state: 'open', service: 'SDK' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-001',
        cve_id: 'CVE-2021-36260',
        severity: 'critical',
        cvss_score: 9.8,
        description: 'Command injection vulnerability in Hikvision IP cameras',
        remediation: 'Update firmware to version 5.5.800 or later immediately',
        affected_devices: ['dev-002'],
        references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-36260'],
        published_date: '2021-09-22',
        last_modified: '2023-08-08',
        aiRiskScore: 0.95, 
        confidence: 'HIGH',
        category: 'vulnerability',
        status: 'confirmed'
      },
      {
        id: 'vuln-cam-002',
        cve_id: 'RTSP-NO-AUTH',
        severity: 'high',
        cvss_score: 7.5,
        description: 'RTSP stream accessible without authentication',
        remediation: 'Enable authentication for RTSP stream in camera settings',
        affected_devices: ['dev-002'],
        references: [],
        published_date: '2024-01-01',
        last_modified: '2024-01-01',
        aiRiskScore: 0.8,
        confidence: 'MEDIUM',
        category: 'misconfiguration',
        status: 'potential'
      }
    ],
    riskLevel: 'critical',
    services: ['HTTP', 'RTSP'],
    lastSeen: new Date().toISOString(),
    firstSeen: '2024-02-01T14:20:00Z',
    aiConfidence: 0.9,
    osPrediction: { os: 'Embedded Linux', confidence: 0.85 },
    detectedVendor: 'Hikvision Digital Technology',
    mlFeatures: ['camera_ports', 'rtsp', 'http']
  },
  {
    id: 'dev-003',
    ip: '192.168.1.15',
    mac: 'AA:BB:CC:DD:EE:03',
    vendor: 'Nest',
    type: 'thermostat',
    hostname: 'living-room-thermostat',
    ports: [
      { number: 443, protocol: 'tcp', state: 'open', service: 'HTTPS' },
      { number: 9543, protocol: 'tcp', state: 'open', service: 'Weave' },
    ],
    vulnerabilities: [],
    riskLevel: 'low',
    services: ['HTTPS', 'Weave'],
    lastSeen: new Date().toISOString(),
    firstSeen: '2024-01-20T09:15:00Z',
    aiConfidence: 0.85,
    osPrediction: { os: 'Linux (Nest)', confidence: 0.8 },
    mlFeatures: ['iot_ports', 'weave']
  },
  {
    id: 'dev-004',
    ip: '192.168.1.20',
    mac: 'AA:BB:CC:DD:EE:04',
    vendor: 'TP-Link',
    type: 'smart_speaker',
    hostname: 'kitchen-speaker',
    ports: [
      { number: 80, protocol: 'tcp', state: 'open', service: 'HTTP' },
      { number: 443, protocol: 'tcp', state: 'open', service: 'HTTPS' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-002',
        cve_id: 'CVE-2023-27217',
        severity: 'high',
        cvss_score: 7.5,
        description: 'Buffer overflow in TP-Link smart devices',
        remediation: 'Apply security patch from manufacturer. Isolate device if patch unavailable.',
        affected_devices: ['dev-004'],
        references: ['https://nvd.nist.gov/vuln/detail/CVE-2023-27217'],
        published_date: '2023-04-15',
        last_modified: '2023-09-01',
        aiRiskScore: 0.72,
        confidence: 'MEDIUM',
        category: 'vulnerability',
        status: 'potential'
      },
    ],
    riskLevel: 'high',
    services: ['HTTP', 'HTTPS'],
    lastSeen: new Date().toISOString(),
    firstSeen: '2024-03-05T16:45:00Z',
    aiConfidence: 0.8,
    osPrediction: { os: 'Linux (Embedded)', confidence: 0.75 },
    mlFeatures: ['speaker_ports', 'upnp']
  },
  {
    id: 'dev-005',
    ip: '192.168.1.25',
    mac: 'AA:BB:CC:DD:EE:05',
    vendor: 'Samsung',
    type: 'smart_tv',
    hostname: 'living-room-tv',
    ports: [
      { number: 8001, protocol: 'tcp', state: 'open', service: 'Samsung TV' },
      { number: 8002, protocol: 'tcp', state: 'open', service: 'Samsung TV SSL' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-003',
        cve_id: 'CVE-2022-1234',
        severity: 'medium',
        cvss_score: 5.3,
        description: 'Information disclosure in Samsung Smart TV API',
        remediation: 'Update TV firmware to latest version via Settings > Support > Software Update',
        affected_devices: ['dev-005'],
        references: ['https://nvd.nist.gov/vuln/detail/CVE-2022-1234'],
        published_date: '2022-06-10',
        last_modified: '2022-12-01',
        aiRiskScore: 0.5,
        confidence: 'HIGH',
        category: 'vulnerability',
        status: 'confirmed'
      },
    ],
    riskLevel: 'medium',
    services: ['Samsung TV API'],
    lastSeen: new Date().toISOString(),
    firstSeen: '2024-01-10T11:00:00Z',
    aiConfidence: 0.85,
    osPrediction: { os: 'Tizen OS', confidence: 0.9 },
    mlFeatures: ['tv_ports', 'upnp']
  },
  {
    id: 'dev-006',
    ip: '192.168.1.100',
    mac: 'AA:BB:CC:DD:EE:06',
    vendor: 'Dell',
    type: 'computer',
    hostname: 'workstation-01',
    os: 'Windows 11 Pro',
    ports: [
      { number: 135, protocol: 'tcp', state: 'open', service: 'MSRPC' },
      { number: 445, protocol: 'tcp', state: 'open', service: 'SMB' },
      { number: 3389, protocol: 'tcp', state: 'open', service: 'RDP' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-win-001',
        cve_id: 'SMB-SIGNING-DISABLED',
        severity: 'medium',
        cvss_score: 5.0,
        description: 'SMB Signing not required',
        remediation: 'Enable SMB Signing via Group Policy',
        affected_devices: ['dev-006'],
        references: [],
        published_date: '2024-01-01',
        last_modified: '2024-01-01',
        aiRiskScore: 0.6,
        confidence: 'HIGH',
        category: 'misconfiguration',
        status: 'confirmed'
      },
      {
        id: 'vuln-win-002',
        cve_id: 'RDP-EXPOSED',
        severity: 'high',
        cvss_score: 7.0,
        description: 'RDP Service exposed to network',
        remediation: 'Restrict RDP access to specific IPs or use VPN',
        affected_devices: ['dev-006'],
        references: [],
        published_date: '2024-01-01',
        last_modified: '2024-01-01',
        aiRiskScore: 0.7,
        confidence: 'HIGH',
        category: 'exposure',
        status: 'confirmed'
      }
    ],
    riskLevel: 'high',
    services: ['MSRPC', 'SMB', 'RDP'],
    lastSeen: new Date().toISOString(),
    firstSeen: '2024-01-05T08:30:00Z',
    aiConfidence: 0.98,
    osPrediction: { os: 'Windows 11', confidence: 0.95 },
    mlFeatures: ['windows_ports', 'smb', 'rdp']
  },
  {
    id: 'dev-007',
    ip: '192.168.1.150',
    mac: 'AA:BB:CC:DD:EE:07',
    vendor: 'Synology',
    type: 'nas',
    hostname: 'home-nas',
    os: 'DSM 7.2',
    ports: [
      { number: 5000, protocol: 'tcp', state: 'open', service: 'HTTP' },
      { number: 5001, protocol: 'tcp', state: 'open', service: 'HTTPS' },
      { number: 22, protocol: 'tcp', state: 'open', service: 'SSH' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-004',
        cve_id: 'CVE-2024-0001',
        severity: 'low',
        cvss_score: 3.1,
        description: 'Minor information leak in Synology DSM',
        remediation: 'Update to DSM 7.2.1 or later',
        affected_devices: ['dev-007'],
        references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-0001'],
        published_date: '2024-01-02',
        last_modified: '2024-02-15',
        aiRiskScore: 0.4,
        confidence: 'LOW',
        category: 'vulnerability',
        status: 'unverified'
      },
    ],
    riskLevel: 'low',
    services: ['HTTP', 'HTTPS', 'SSH'],
    lastSeen: new Date().toISOString(),
    firstSeen: '2024-01-08T13:20:00Z',
    aiConfidence: 0.92,
    osPrediction: { os: 'Synology DSM (Linux)', confidence: 0.9 },
    mlFeatures: ['nas_ports', 'http', 'ssh']
  },
  {
    id: 'dev-008',
    ip: '192.168.1.200',
    mac: 'AA:BB:CC:DD:EE:08',
    vendor: 'Philips',
    type: 'sensor',
    hostname: 'hue-bridge',
    ports: [
      { number: 80, protocol: 'tcp', state: 'open', service: 'HTTP' },
      { number: 443, protocol: 'tcp', state: 'open', service: 'HTTPS' },
      { number: 23, protocol: 'tcp', state: 'open', service: 'Telnet' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-telnet-001',
        cve_id: 'TELNET-EXPOSED',
        severity: 'critical',
        cvss_score: 9.0,
        description: 'Unencrypted Telnet service detected',
        remediation: 'Replace with SSH immediately. Telnet transmits credentials in plain text.',
        affected_devices: ['dev-008'],
        references: [],
        published_date: '2024-01-01',
        last_modified: '2024-01-01',
        aiRiskScore: 0.9,
        confidence: 'HIGH',
        category: 'misconfiguration',
        status: 'confirmed'
      }
    ],
    riskLevel: 'critical',
    services: ['HTTP', 'HTTPS', 'Telnet'],
    lastSeen: new Date().toISOString(),
    firstSeen: '2024-02-10T10:00:00Z',
    aiConfidence: 0.88,
    osPrediction: { os: 'Embedded Linux', confidence: 0.85 },
    mlFeatures: ['iot_ports', 'http']
  },
];
export const mockInterfaces: NetworkInterface[] = [
  {
    name: 'eth0',
    displayName: 'Ethernet (Primary)',
    ip: '192.168.1.50',
    netmask: '255.255.255.0',
    mac: 'DE:AD:BE:EF:00:01',
    type: 'ethernet',
    status: 'up',
    isDefault: true,
  },
  {
    name: 'wlan0',
    displayName: 'Wi-Fi',
    ip: '192.168.1.51',
    netmask: '255.255.255.0',
    mac: 'DE:AD:BE:EF:00:02',
    type: 'wifi',
    status: 'up',
    isDefault: false,
  },
  {
    name: 'docker0',
    displayName: 'Docker Bridge',
    ip: '172.17.0.1',
    netmask: '255.255.0.0',
    mac: 'DE:AD:BE:EF:00:03',
    type: 'virtual',
    status: 'up',
    isDefault: false,
  },
];
export const mockScanStatus: ScanStatus = {
  id: 'scan-001',
  status: 'idle',
  mode: 'quick',
  progress: 0,
  devicesScanned: 0,
  totalDevices: 0,
  vulnerabilitiesFound: 0,
  interface: 'eth0',
};
export const mockReports: ScanReport[] = [
  {
    id: 'report-001',
    scanId: 'scan-prev-001',
    timestamp: '2024-12-27T14:30:00Z',
    duration: 245,
    mode: 'comprehensive',
    interface: 'eth0',
    summary: {
      totalDevices: 8,
      newDevices: 0,
      vulnerableDevices: 4,
      totalVulnerabilities: 5,
      criticalCount: 1,
      highCount: 1,
      mediumCount: 2,
      lowCount: 1,
    },
    devices: mockDevices,
    vulnerabilities: mockDevices.flatMap(d => d.vulnerabilities),
  },
  {
    id: 'report-002',
    scanId: 'scan-prev-002',
    timestamp: '2024-12-26T10:15:00Z',
    duration: 180,
    mode: 'deep',
    interface: 'eth0',
    summary: {
      totalDevices: 7,
      newDevices: 1,
      vulnerableDevices: 3,
      totalVulnerabilities: 4,
      criticalCount: 1,
      highCount: 1,
      mediumCount: 1,
      lowCount: 1,
    },
    devices: mockDevices.slice(0, 7),
    vulnerabilities: mockDevices.slice(0, 7).flatMap(d => d.vulnerabilities),
  },
  {
    id: 'report-003',
    scanId: 'scan-prev-003',
    timestamp: '2024-12-25T08:00:00Z',
    duration: 60,
    mode: 'quick',
    interface: 'wlan0',
    summary: {
      totalDevices: 5,
      newDevices: 0,
      vulnerableDevices: 2,
      totalVulnerabilities: 2,
      criticalCount: 0,
      highCount: 1,
      mediumCount: 1,
      lowCount: 0,
    },
    devices: mockDevices.slice(0, 5),
    vulnerabilities: mockDevices.slice(0, 5).flatMap(d => d.vulnerabilities),
  },
];
export const mockLogs: LogEntry[] = [
  {
    id: 'log-001',
    timestamp: new Date().toISOString(),
    level: 'info',
    message: 'System initialized successfully',
    source: 'system',
  },
  {
    id: 'log-002',
    timestamp: new Date(Date.now() - 60000).toISOString(),
    level: 'info',
    message: 'Network interface eth0 detected: 192.168.1.50',
    source: 'network',
  },
  {
    id: 'log-003',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    level: 'warning',
    message: 'Device 192.168.1.10 has critical vulnerabilities',
    source: 'scanner',
  },
  {
    id: 'log-004',
    timestamp: new Date(Date.now() - 180000).toISOString(),
    level: 'info',
    message: 'CVE database updated: 2,847 new entries',
    source: 'cve-db',
  },
  {
    id: 'log-005',
    timestamp: new Date(Date.now() - 240000).toISOString(),
    level: 'debug',
    message: 'ARP scan completed on 192.168.1.0/24',
    source: 'scanner',
  },
  {
    id: 'log-006',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    level: 'error',
    message: 'Failed to connect to device 192.168.1.99: timeout',
    source: 'scanner',
  },
  {
    id: 'log-007',
    timestamp: new Date(Date.now() - 360000).toISOString(),
    level: 'info',
    message: 'Port scan completed on 192.168.1.1',
    source: 'scanner',
  },
  {
    id: 'log-008',
    timestamp: new Date(Date.now() - 420000).toISOString(),
    level: 'warning',
    message: 'Outdated firmware detected on device 192.168.1.20',
    source: 'analyzer',
  },
];
export const mockDashboardStats: DashboardStats = {
  totalDevices: mockDevices.length,
  vulnerableDevices: mockDevices.filter(d => d.vulnerabilities.length > 0).length,
  activeScans: 0,
  criticalVulnerabilities: mockDevices.flatMap(d => d.vulnerabilities).filter(v => v.severity === 'critical').length,
  highVulnerabilities: mockDevices.flatMap(d => d.vulnerabilities).filter(v => v.severity === 'high').length,
  mediumVulnerabilities: mockDevices.flatMap(d => d.vulnerabilities).filter(v => v.severity === 'medium').length,
  lowVulnerabilities: mockDevices.flatMap(d => d.vulnerabilities).filter(v => v.severity === 'low').length,
  lastScanTime: '2024-12-27T14:30:00Z',
};
export const mockActivity: ActivityItem[] = [
  {
    id: 'act-001',
    type: 'scan_completed',
    message: 'Comprehensive scan completed on eth0',
    timestamp: '2024-12-27T14:30:00Z',
  },
  {
    id: 'act-002',
    type: 'vulnerability_detected',
    message: 'Critical vulnerability CVE-2021-36260 found on front-door-cam',
    timestamp: '2024-12-27T14:25:00Z',
    severity: 'critical',
  },
  {
    id: 'act-003',
    type: 'device_found',
    message: 'New device discovered: 192.168.1.200 (Philips)',
    timestamp: '2024-12-26T10:20:00Z',
  },
  {
    id: 'act-004',
    type: 'scan_started',
    message: 'Deep scan initiated on eth0',
    timestamp: '2024-12-26T10:15:00Z',
  },
  {
    id: 'act-005',
    type: 'alert',
    message: 'Multiple failed login attempts detected from external IP',
    timestamp: '2024-12-25T22:00:00Z',
    severity: 'high',
  },
];
export const mockSettings: Settings = {
  apiEndpoint: 'http://localhost:5000/api',
  defaultInterface: 'eth0',
  autoRefreshInterval: 30,
  logRetentionDays: 30,
  aiModelEnabled: true,
  aiModelStatus: 'online',
};
export const mockVulnerabilities: Vulnerability[] = mockDevices.flatMap(d => d.vulnerabilities);